export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';



export const START_DOWNLOAD_USERS = 'START_DOWNLOAD_USERS';
export const DOWNLOAD_USERS_SUCCESS = 'DOWNLOAD_USERS_SUCCESS';
export const DOWNLOAD_USERS_FAILURE = 'DOWNLOAD_USERS_FAILURE';