name: React CI

on:
  push:
    branches:
      - master
defaults: 
  run: 
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: chrislennon/action-aws-cli@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET}}
        env:
          AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'dist'